[versions]
asciidoctor-gradle-jvm = '4.0.2'
assetpipeline = '4.4.0'
grails-gradle-plugin = '6.1.2'
grails-views = '3.2.2'
groovy-doc = '1.0.1'
nexus-publish-gradle-plugin = '1.3.0'

[libraries]
asciidoctor-gradle-plugin = { module = 'org.asciidoctor:asciidoctor-gradle-jvm', version.ref = 'asciidoctor-gradle-jvm' }
assetpipeline-gradle-plugin = { module = 'com.bertramlabs.plugins:asset-pipeline-gradle', version.ref = 'assetpipeline' }
grails-gradle-plugin = { module = 'org.grails:grails-gradle-plugin', version.ref = 'grails-gradle-plugin' }
grails-views-gradle-plugin = { module = 'org.grails.plugins:views-gradle', version.ref = 'grails-views' }
nexus-publish-gradle-plugin = { module = 'io.github.gradle-nexus:publish-plugin', version.ref = 'nexus-publish-gradle-plugin' }
groovydoc-gradle-plugin = { module = 'io.github.groovylang.groovydoc:groovydoc-gradle-plugin', version.ref = 'groovy-doc' }
